"""Application-wide constants."""

from __future__ import annotations

DEFAULT_CURRENCY = "USD"
DEFAULT_TIMEZONE = "UTC"
MIN_PASSWORD_LENGTH = 8
MAX_SKU_LENGTH = 64
MAX_PRODUCT_NAME_LENGTH = 255
ORDER_NUMBER_PREFIX = "ORD"
TRANSFER_NUMBER_PREFIX = "TRF"
RESERVATION_TTL_HOURS = 24
REPORT_CACHE_PREFIX = "report:"
INVENTORY_CACHE_PREFIX = "inventory:"
PRODUCT_CACHE_PREFIX = "product:"
